---
- hosts: all
  become: yes
  become_user: isucon
  gather_facts: no
  tags:
    - dev
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # perl
    - command: /home/isucon/.xbuild/perl-install 5.24.0 /home/isucon/.local/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.3.1 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v6.5.0 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
    # golang
    - command: /home/isucon/.xbuild/go-install 1.7 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go
    # php
    - command: /home/isucon/.xbuild/php-install 7.0.10 /home/isucon/.local/php -- --disable-phar --with-pcre-regex --with-zlib --enable-fpm --enable-pdo --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-openssl --with-pcre-regex --with-pcre-dir --with-libxml-dir --enable-opcache --enable-bcmath --with-bz2 --enable-calendar --enable-cli --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-mbregex --enable-mbstring --with-mcrypt --enable-pcntl --enable-sockets --with-curl --enable-zip --with-pear
      args:
        creates: /home/isucon/.local/php/bin/php

- hosts: all
  become: yes
  gather_facts: no
  tags:
    - prod
  tasks:
    - unarchive:
        copy=no
        src=https://isucon6qimage.example.com/isucon6q/local.tar.gz
        dest=/home/isucon/
        creates=/home/isucon/.local
        owner=isucon
        group=isucon
