---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - debconf: name=mysql-server-5.7 question='mysql-server/root_password' value='root' vtype='password'
    - debconf: name=mysql-server-5.7 question='mysql-server/root_password_again' value='root' vtype='password'
    - apt: name=mysql-server-5.7 state=present
    - apt: name=mysql-client-5.7 state=present
    - name: copy my.cnf
      copy: src=../files/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=644
      notify:
        - restart mysql
    - service: name=mysql state=running enabled=true
    - file: path=/home/isucon/isu6qportal/db owner=isucon group=isucon mode=755 state=directory recurse=yes
    - copy: src=../../../portal/db/schema.sql dest=/home/isucon/isu6qportal/db/schema.sql
    - shell: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot -proot mysql
    - shell: |
        for d in $(seq 0 2); do
          mysql -uroot -proot -e "CREATE DATABASE isu6qportal_day$d"
          mysql -uroot -proot isu6qportal_day$d < /home/isucon/isu6qportal/db/schema.sql
          mysql -uroot -proot isu6qportal_day$d -e "REPLACE INTO setting (name, json) VALUES ('day', '$d')";
        done
  handlers:
    - name: restart mysql
      action: service name=mysql state=restarted
